"""
paths.py - Canonical filesystem locations for the RBM-plankton working tree.
============================================================================
pyproject.toml makes `models` importable from any working directory (editable
install, package-dir = code/src).  It says nothing about *where* the dataset,
the trained runs and the outputs live.  This module is the single place that
does: every script imports these constants instead of re-deriving the repo root
from its own __file__ depth, which is how `trained_models/` (documented) and
`training_runs/` (actual, now `artifacts/models/`) once drifted apart.

The paths are not declared in pyproject.toml on purpose — reading it at runtime
would first require locating it, which is the same root-finding problem plus a
tomllib dependency.

Override the root when the working tree is not the parent of this source file:
    RBM_PLANKTON_ROOT=/data/rbm-plankton python code/scripts/diagnostic/sweep_analysis.py
"""

import os
from pathlib import Path

# Repo root: code/src/models/paths.py -> models -> src -> code -> root.
_SOURCE_ROOT = Path(__file__).resolve().parents[3]

PROJECT_ROOT = Path(os.environ.get("RBM_PLANKTON_ROOT") or _SOURCE_ROOT)

# Raw CSV: daily plankton counts, 83 taxa, organisms/uL.
# Gitignored — the user must provide it (see README).
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "TimeSeries_countsuL_clean.csv"

# Trained model weights, one directory per (family, L, split): see io.model_dir().
# Gitignored — regenerated by code/scripts/train/train.py.  Lives under artifacts/
# rather than a plain "runs" tier because every seed's weights.npz is consumed
# by many downstream analysis scripts, not just the run that produced it.
MODELS_ROOT = PROJECT_ROOT / "artifacts" / "models"

# Tracked figures and tables that back the report.
RESULTS_ROOT = PROJECT_ROOT / "results"

# Untracked evaluation artefacts (training curves, sweep diagnostics, NaN eval).
DIAGNOSTIC_ROOT = PROJECT_ROOT / "diagnostic_outputs"


# -- Split strategies ----------------------------------------------------------

# The train/val split strategy is a comparison axis, not a naming detail: it
# decides whether the validation rows are i.i.d. (shuffled) or a future window
# (chronological).  Scripts carry one of these two values and convert it to a
# directory suffix only at the filesystem boundary, via model_dir().
#
# They live here, next to the paths, rather than in io.py: this module imports
# nothing beyond os and pathlib, so train.py and config.py can name a split
# without pulling torch into the parent process before the worker pool forks.
CHRONO   = "chrono"
SHUFFLED = "shuffled"
SPLITS   = (CHRONO, SHUFFLED)

_SPLIT_SUFFIX = {CHRONO: "", SHUFFLED: "_shuffled"}


def split_suffix(split: str) -> str:
    """Run-directory suffix for a split strategy ('' or '_shuffled')."""
    if split not in _SPLIT_SUFFIX:
        raise ValueError(f"Unknown split={split!r}; expected one of {SPLITS}.")
    return _SPLIT_SUFFIX[split]


def model_dir(family: str, n_hidden: int, split: str = CHRONO,
              models_root: Path = MODELS_ROOT) -> Path:
    """Directory holding the seeds of one (family, L, split) trained model."""
    if split not in SPLITS:
        raise ValueError(f"Unknown split={split!r}; expected one of {SPLITS}.")
    return Path(models_root) / family / split / f"L{n_hidden}"


def split_out_dir(base: Path, split: str) -> Path:
    """Output convention: base/chrono/ or base/shuffled/, symmetric and labelled."""
    if split not in _SPLIT_SUFFIX:
        raise ValueError(f"Unknown split={split!r}; expected one of {SPLITS}.")
    return Path(base) / split
